version: '3'

services:
  db:
    image: mysql
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - type: bind
        source: ${MYSQL_DATA_DIR}
        target: /var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${DB_PASSWORD}

  wordpress:
    depends_on:
       - db
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: ./wordpress
    volumes:
      - type: bind
        source: ${WORDPRESS_DIR}
        target: /var/www/html
      - type: bind
        source: ${WORDPRESS_CONTENT_DIR}
        target: /var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_POST_REVISIONS', 10);
        define('FS_METHOD','direct');

  apache:
    depends_on:
      - wordpress
      - db
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: ./httpd
      dockerfile: Dockerfile
      args:
        userid: "${USER_ID}"
        groupid: "${GROUP_ID}"
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - type: bind
        source: ${WORDPRESS_DIR}
        target: /var/www/html
      - type: bind
        source: ${WORDPRESS_CONTENT_DIR}
        target: /var/www/html/wp-content
    restart: always
